import React, { createContext, useContext, useState, useEffect } from 'react';

// Translation data
const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.articles': 'Articles',
    'nav.about': 'About',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contact',
    'nav.login': 'Login',
    'nav.signup': 'Sign Up',
    'nav.profile': 'Profile',
    'nav.dashboard': 'Dashboard',
    'nav.logout': 'Logout',
  // Researcher
  'nav.work': 'Work With Us',
    
    // Homepage
    'hero.title.part1': 'International Center for',
    'hero.title.part2': 'Scientific Research & Translation',
    'hero.description': 'Empowering academic excellence through expert research assistance.',
    'hero.btn.services': 'Explore Services',
    'hero.btn.learn': 'Learn More',
    'hero.badge': 'Trusted Research Partner',
    
    // Stats
    'stats.clients': 'Customers',
    'stats.countries': 'Countries Served',
    'stats.success': 'Projects Completed',
    'stats.support': 'Support',
    'stats.visitors': 'Academic Partners',
    
    // Services
    'services.title': 'Our Services',
    'services.subtitle': 'Professional research and academic services',
    'services.description': 'We provide comprehensive research and academic support services',
    'services.view': 'View Details',
    'services.request': 'Request Service',
    'services.research.title': 'Research Assistance',
    'services.research.desc': 'Expert guidance for your research projects from conception to completion.',
    'services.translation.title': 'Professional Translation',
    'services.translation.desc': 'Accurate translations by certified linguists across multiple languages.',
    'services.graduation.title': 'Graduation Projects',
    'services.graduation.desc': 'Complete support for thesis and dissertation development.',
    'services.cta.title': 'Ready to Get Started?',
    'services.cta.description': 'Contact us today to discuss your research needs and get a customized solution.',
    'services.cta.button': 'Get Started Now',
    
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.search': 'Search',
    'common.close': 'Close',
    'common.settings': 'Settings',
    
    // Form labels
    'form.name': 'Full Name',
    'form.email': 'Email Address',
    'form.phone': 'Phone Number',
    'form.subject': 'Subject',
    'form.message': 'Message',
    'form.category': 'Category',
    'form.submit': 'Submit',
    'form.send': 'Send Message',
    'form.sending': 'Sending...',
    
    // Contact
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Get in touch with our team',
    'contact.description': 'We\'re here to help with your research and academic needs',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.phone': 'Phone Number',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.category': 'Category',
    'contact.form.submit': 'Send Message',
    'contact.form.send': 'Send Message',
    'contact.form.sending': 'Sending...',
    'contact.form.namePlaceholder': 'Enter your full name',
    'contact.form.emailPlaceholder': 'Enter your email address',
    'contact.form.phonePlaceholder': 'Enter your phone number',
    'contact.form.subjectPlaceholder': 'Brief description of your inquiry',
    'contact.form.messagePlaceholder': 'Describe your needs or questions in detail',
    'contact.success': 'Message sent successfully!',
    'contact.success.title': 'Message Sent!',
    'contact.success.message': 'Thank you for contacting us. We\'ll get back to you soon.',
    'contact.error': 'Failed to send message. Please try again.',
    'contact.category.general': 'General Inquiry',
    'contact.category.services': 'Services Information',
    'contact.category.technical': 'Technical Support',
    'contact.category.billing': 'Billing & Payments',
    'contact.category.partnership': 'Partnership',
    'contact.info.email.title': 'Email Us',
    'contact.info.email.value': 'info@icsrt-me.com',
    'contact.info.phone.title': 'Call Us',
    'contact.info.phone.value': '+20 101 804 5506',
    'contact.info.response.title': 'Response Time',
    'contact.info.response.value': 'Within 24 hours',
    'contact.whatsapp': 'Chat with us on WhatsApp',
    'contact.telegram': 'Message us on Telegram',
    'contact.submitTicket': 'Submit Support Ticket',
    'contact.getHelp': 'Get professional help',
    
    // Articles
    'articles.title': 'Research Articles',
    'articles.subtitle': 'Latest research insights and publications',
    'articles.view': 'Read More',
    'articles.read': 'Read Article',
    'articles.1.title': 'Effective Research Methodology for Modern Academic Studies',
    'articles.1.desc': 'Discover comprehensive methodologies for conducting rigorous academic research in the digital age. Learn about mixed-methods approaches, data collection strategies, and ethical considerations that form the foundation of credible scientific inquiry.',
    'articles.2.title': 'The Art of Scientific Translation: Bridging Languages in Research',
    'articles.2.desc': 'Explore the specialized field of scientific translation where precision meets linguistic expertise. Understanding terminology, cultural nuances, and maintaining scientific accuracy across language barriers in academic publications.',
    'articles.3.title': 'Digital Tools and Resources for Contemporary Research',
    'articles.3.desc': 'Navigate the landscape of modern research tools including AI-powered analysis, cloud-based collaboration platforms, citation management systems, and data visualization techniques that enhance research quality and efficiency.',
    
    // About
    'about.title': 'About ICSRT',
    'about.description': 'International Center for Scientific Research and Translation - Your trusted partner in academic excellence',
    'about.bio.title': 'Our Story',
    'about.mission.title': 'Our Mission',
    'about.mission.description': 'To provide exceptional academic services and support to students, researchers, and institutions worldwide.',
    'about.vision.title': 'Our Vision',
    'about.vision.description': 'To become the leading international platform for scientific research and translation services.',
    'about.approach.title': 'Our Approach',
    'about.excellence.title': 'Excellence',
    'about.excellence.description': 'We maintain the highest standards in academic research and professional services, ensuring every project meets international quality benchmarks.',
    'about.collaboration.title': 'Collaboration',
    'about.collaboration.description': 'We work closely with researchers, institutions, and academic communities worldwide to foster knowledge sharing and innovation.',
    'about.innovation.title': 'Innovation',
    'about.innovation.description': 'We embrace cutting-edge technologies and methodologies to provide modern solutions for contemporary research challenges.',
    'about.impact.title': 'Our Impact',
    'about.stats.clients': 'Customers',
    'about.stats.countries': 'Countries Served',
    'about.stats.projects': 'Projects Completed',
    'about.stats.success': 'Support',
    'about.cta.title': 'Ready to Start Your Research Journey?',
    'about.cta.description': 'Join thousands of researchers who trust us with their academic success. Let us help you achieve your research goals.',
    'about.cta.services': 'Explore Our Services',
    'about.cta.portal': 'Access Research Portal',
    'about.learn.more': 'Learn More About Us',

    // Common translations
    'common.statistics': 'Statistics',

    // Service request section
    'serviceRequest.title': 'Request a Service',
    'serviceRequest.subtitle': 'Get our specialized academic services',
    'serviceRequest.form.title': 'Service Request Form',
    'serviceRequest.form.fullName': 'Full Name',
    'serviceRequest.form.fullName.placeholder': 'Enter your full name',
    'serviceRequest.form.email': 'Email Address',
    'serviceRequest.form.email.placeholder': 'Enter your email address',
    'serviceRequest.form.phone': 'Phone Number',
    'serviceRequest.form.phone.placeholder': 'Enter your phone number',
    'serviceRequest.form.serviceType': 'Service Type',
    'serviceRequest.form.serviceType.placeholder': 'Select Service Type',
    'serviceRequest.form.serviceType.research': 'Research & Assignments',
    'serviceRequest.form.serviceType.translation': 'Translation Services',
    'serviceRequest.form.serviceType.graduation': 'Graduation Projects',
    'serviceRequest.form.serviceType.thesis': 'Master\'s & PhD Thesis',
    'serviceRequest.form.serviceType.editing': 'Editing & Proofreading',
    'serviceRequest.form.serviceType.consultation': 'Academic Consultation',
    'serviceRequest.form.urgency': 'Urgency Level',
    'serviceRequest.form.urgency.normal': 'Normal',
    'serviceRequest.form.urgency.urgent': 'Urgent', 
    'serviceRequest.form.urgency.veryUrgent': 'Very Urgent',
    'serviceRequest.form.projectDetails': 'Project Details',
    'serviceRequest.form.projectDetails.placeholder': 'Describe the project or service you need...',
    'serviceRequest.form.submit': 'Submit Service Request',
    'serviceRequest.form.response': 'We will contact you within 24 hours',
    'serviceRequest.login.required': 'You must be logged in to submit service requests',
    'serviceRequest.login.button': 'Login',
    'serviceRequest.features.quick.title': 'Quick Response',
    'serviceRequest.features.quick.desc': 'We respond within 24 hours',
    'serviceRequest.features.quality.title': 'High Quality',
    'serviceRequest.features.quality.desc': 'International academic standards',
    'serviceRequest.features.privacy.title': 'Full Privacy',
    'serviceRequest.features.privacy.desc': 'Complete protection of your data',

    // Footer
    'footer.about.title': 'ICSRT',
    'footer.about.desc': 'International Conference on Science, Research and Technology. Advancing scientific knowledge and fostering global collaboration.',
  'footer.description': 'International Conference on Science, Research and Technology. Advancing scientific knowledge and fostering global collaboration.',
    'footer.quickLinks.title': 'Quick Links',
    'footer.quickLinks.about': 'About Us',
    'footer.quickLinks.events': 'Events',
    'footer.quickLinks.papers': 'Research Papers',
    'footer.quickLinks.services': 'Services',
    'footer.contact.title': 'Contact',
    'footer.contact.email': 'Email: info@icsrt.org',
    'footer.contact.phone': 'Phone: +1 (555) 123-4567',
    'footer.contact.support': 'Support: support@icsrt.org',
    'footer.newsletter.title': 'Stay Updated',
    'footer.newsletter.desc': 'Subscribe to our newsletter for the latest updates.',
    'footer.newsletter.subscribe': 'Subscribe',
    'footer.copyright': '© {year} ICSRT. All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    
    // Theme
    'theme.dark': 'Switch to Dark Mode',
    'theme.light': 'Switch to Light Mode',
    
    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Find answers to common questions about our services',
    'faq.stillHaveQuestions': 'Still have questions?',
    'faq.contactUs': 'We\'re here to help you with any additional questions.',
    'faq.contactButton': 'Contact Us',
    
    // Login
    'login.welcome': 'Welcome Back',
    'login.subtitle': 'Sign in to your account to access all features',
    'login.signing': 'Signing in...',
    'login.forgot': 'Forgot Password?',
    'login.no.account': 'Don\'t have an account?',
    'login.signup.link': 'Sign up here',
    'form.login': 'Sign In',
    'form.password': 'Password',
  // Forgot / Reset Password
  'forgot.title': 'Forgot Password',
  'forgot.subtitle': 'Enter your email to receive a reset link',
  'forgot.submit': 'Send Reset Link',
  'forgot.sending': 'Sending...',
  'forgot.sent': 'If an account exists for this email, a reset link has been sent.',
  'forgot.backToLogin': 'Back to Login',
  'reset.title': 'Reset Password',
  'reset.subtitle': 'Enter a new password for your account',
  'reset.password': 'New Password',
  'reset.confirm': 'Confirm New Password',
  'reset.submit': 'Save New Password',
  'reset.saving': 'Saving...',
  'reset.invalid': 'Invalid or expired reset link',
  'reset.success': 'Password has been reset. You can now log in.',
    
    // SignUp
    'signup.title': 'Create Account',
    'signup.subtitle': 'Join our research community',
    'signup.creating': 'Creating account...',
    'signup.already.account': 'Already have an account?',
    'signup.login.link': 'Sign in here',
    'form.signup': 'Sign Up',
    'form.confirmPassword': 'Confirm Password',
    'form.institution': 'Institution',
    'form.country': 'Country',
    'form.userType': 'User Type',
    'form.userType.student': 'Student',
    'form.userType.researcher': 'Researcher',
    'form.userType.professor': 'Professor',
    'form.userType.other': 'Other',
    'signup.password.requirements': 'Password Requirements:',
    'signup.password.length': 'At least 8 characters',
    'signup.password.uppercase': 'One uppercase letter',
    'signup.password.lowercase': 'One lowercase letter',
    'signup.password.number': 'One number',
    'signup.password.special': 'One special character',
    'signup.password.match': 'Passwords must match',
    'signup.terms': 'I agree to the Terms of Service and Privacy Policy',
    
    // Purchase Page
    'purchase.title': 'Complete Your Purchase',
    'purchase.loading': 'Loading purchase details...',
    'purchase.error': 'Error loading purchase details',
    'purchase.invalid': 'Invalid or expired purchase link',
    'purchase.completed': 'Purchase completed successfully!',
    'purchase.orderSummary': 'Order Summary',
    'purchase.billingInfo': 'Billing Information',
    'purchase.paymentMethod': 'Payment Method',
    'purchase.couponCode': 'Coupon Code',
    'purchase.applyCoupon': 'Apply Coupon',
    'purchase.discount': 'Discount',
    'purchase.subtotal': 'Subtotal',
    'purchase.total': 'Total',
    'purchase.processing': 'Processing Payment...',
    'purchase.completePurchase': 'Complete Purchase',
    
    // Email Verification
    'verification.title': 'Verify Your Email',
    'verification.subtitle': 'Enter the verification code sent to your email address.',
    'verification.email': 'Email Address',
    'verification.emailPlaceholder': 'Enter your email address',
    'verification.code': 'Verification Code',
    'verification.codeHelp': 'Enter the 6-character code from your email',
    'verification.verifying': 'Verifying...',
    'verification.verify': 'Verify Email',
    'verification.didntReceive': 'Didn\'t receive the code?',
    'verification.resend': 'Resend verification email',
    'verification.backToLogin': 'Back to Login',
    'verification.success': 'Email verified successfully! You can now log in.',
    'verification.error.required': 'Email and verification code are required.',
    'verification.error.network': 'Network error. Please try again.',
    'verification.instructions.title': 'Verification Instructions',
    'verification.instructions.step1': 'Check your email inbox for a verification message from ICSRT',
    'verification.instructions.step2': 'Copy the 6-character verification code from the email',
    'verification.instructions.step3': 'Paste the code in the form above or click the verification link in the email',
    'verification.instructions.step4': 'Check your spam folder if you don\'t see the email within a few minutes',
    
    // Loading and Common Messages
    'msg.loading': 'Loading...',
    
    // Articles
    'articles.read.more': 'Read More',
    
    // User Profile
    'profile.title': 'User Profile',
    'profile.info': 'Profile Information',
    'profile.name': 'Full Name',
    'profile.email': 'Email Address',
    'profile.phone': 'Phone Number',
    'profile.department': 'Department',
    'profile.institution': 'Institution',
    'profile.country': 'Country',
    'profile.bio': 'Biography',
    'profile.edit': 'Edit Profile',
    'profile.save': 'Save Changes',
    'profile.cancel': 'Cancel',
    'profile.success': 'Profile updated successfully!',
    'profile.error': 'Failed to update profile',
    'profile.loading': 'Loading profile...',
    'profile.placeholder.name': 'Enter your full name',
    'profile.placeholder.phone': 'Enter your phone number',
    'profile.placeholder.department': 'Enter your department',
    'profile.placeholder.institution': 'Enter your institution',
    'profile.placeholder.country': 'Enter your country',
    'profile.placeholder.bio': 'Tell us about yourself',
  'profile.changePassword.title': 'Change Password',
  'profile.changePassword': 'Change Password',
  'profile.currentPassword': 'Current Password',
  'profile.newPassword': 'New Password',
  'profile.confirmPassword': 'Confirm New Password',
  'profile.passwordChanged': 'Password changed successfully!',
  'profile.passwordError': 'Failed to change password',
    
    // User Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome back',
    'dashboard.overview': 'Overview',
    'dashboard.stats.tickets': 'Support Tickets',
    'dashboard.stats.orders': 'Service Orders',
    'dashboard.stats.projects': 'Active Projects',
    'dashboard.stats.messages': 'New Messages',
    'dashboard.recent.tickets': 'Recent Tickets',
    'dashboard.recent.orders': 'Recent Service Orders',
    'dashboard.tickets.view': 'View All Tickets',
    'dashboard.orders.view': 'View All Orders',
    'dashboard.tickets.create': 'Create New Ticket',
    'dashboard.orders.create': 'Request New Service',
    'dashboard.ticket.id': 'Ticket ID',
    'dashboard.ticket.subject': 'Subject',
    'dashboard.ticket.status': 'Status',
    'dashboard.ticket.priority': 'Priority',
    'dashboard.ticket.created': 'Created',
    'dashboard.order.number': 'Order #',
    'dashboard.order.service': 'Service',
    'dashboard.order.status': 'Status',
    'dashboard.order.amount': 'Amount',
    'dashboard.order.date': 'Date',
    'dashboard.status.open': 'Open',
    'dashboard.status.progress': 'In Progress',
    'dashboard.status.resolved': 'Resolved',
    'dashboard.status.closed': 'Closed',
    'dashboard.status.pending': 'Pending',
    'dashboard.status.completed': 'Completed',
    'dashboard.status.cancelled': 'Cancelled',
    'dashboard.priority.low': 'Low',
    'dashboard.priority.medium': 'Medium',
    'dashboard.priority.high': 'High',
    'dashboard.priority.urgent': 'Urgent',
    'dashboard.no.tickets': 'No tickets found',
    'dashboard.no.orders': 'No service orders found',
    'dashboard.loading': 'Loading dashboard...',
    'dashboard.todayActivity': "Here's what's happening with your account today.",
    'dashboard.stats.supportTickets': 'Support Tickets',
    'dashboard.stats.serviceOrders': 'Service Orders',
    'dashboard.recentTickets': 'Recent Tickets',
    'dashboard.recentServiceOrders': 'Recent Service Orders',
    'dashboard.noTickets': 'No tickets yet',
    'dashboard.createFirstTicket': 'Create your first ticket',
    'dashboard.noServiceOrders': 'No service orders yet',
    'dashboard.browseServices': 'Browse our services',
    'dashboard.quickActions.supportTickets': 'Support Tickets',
    'dashboard.quickActions.getHelp': 'Get help with your questions',
    'dashboard.quickActions.serviceOrders': 'Service Orders',
    'dashboard.quickActions.viewRequests': 'View your service requests',
    'dashboard.quickActions.browseServices': 'Browse Services',
    'dashboard.quickActions.exploreOfferings': 'Explore our offerings',
    'dashboard.modal.serviceOrderDetails': 'Service Order Details',
    'dashboard.modal.orderInformation': 'Order Information',
    'dashboard.modal.orderNumber': 'Order Number',
    'dashboard.modal.service': 'Service',
    'dashboard.modal.status': 'Status',
    'dashboard.modal.submitted': 'Submitted',
    'dashboard.modal.totalAmount': 'Total Amount',
    'dashboard.modal.serviceDetails': 'Service Details',
    'common.messages': 'msg',
    
    // Admin Dashboard
    'admin.dashboard.title': 'Admin Dashboard',
    'admin.dashboard.welcome': 'Welcome to Admin Panel',
    'admin.dashboard.overview': 'System Overview',
    'admin.dashboard.stats.users': 'Total Users',
    'admin.dashboard.stats.tickets': 'Support Tickets',
    'admin.dashboard.stats.orders': 'Service Orders',
    'admin.dashboard.stats.revenue': 'Monthly Revenue',
    'admin.dashboard.stats.activeProjects': 'Active Projects',
    'admin.dashboard.stats.pendingReviews': 'Pending Reviews',
    'admin.dashboard.recent.activity': 'Recent Activity',
    'admin.dashboard.recent.users': 'New Users',
    'admin.dashboard.recent.tickets': 'Recent Tickets',
    'admin.dashboard.recent.orders': 'Recent Orders',
    'admin.dashboard.manage.users': 'Manage Users',
    'admin.dashboard.manage.tickets': 'Manage Tickets',
    'admin.dashboard.manage.orders': 'Manage Orders',
    'admin.dashboard.manage.services': 'Manage Services',
    'admin.dashboard.analytics': 'Analytics',
    'admin.dashboard.reports': 'Reports',
    'admin.dashboard.settings': 'System Settings',
    
    // Service Orders Page
    'serviceOrders.title': 'My Service Orders',
    'serviceOrders.subtitle': 'Track your orders and communicate with our team',
    'serviceOrders.backToHome': 'Back to Home',
    'serviceOrders.backToDashboard': 'Back to Dashboard',
    'serviceOrders.noOrders': 'No service orders found',
    'serviceOrders.noOrdersDesc': 'Your service orders will appear here once you place them.',
    'serviceOrders.order': 'Order',
    'serviceOrders.viewDetails': 'View Details',
    'serviceOrders.sendMessage': 'Send Message',
    'serviceOrders.purchase': 'Purchase Now',
    'serviceOrders.details': 'Details',
    'serviceOrders.conversation': 'Conversation',
    'serviceOrders.payment': 'Payment',
    'serviceOrders.orderInfo': 'Order Information',
    'serviceOrders.serviceType': 'Service Type',
    'serviceOrders.status': 'Status',
    'serviceOrders.orderDate': 'Order Date',
    'serviceOrders.lastUpdate': 'Last Update',
    'serviceOrders.totalAmount': 'Total Amount',
    'serviceOrders.originalPrice': 'Original Price',
    'serviceOrders.discount': 'Discount',
    'serviceOrders.finalPrice': 'Final Price',
    'serviceOrders.messages': 'Messages',
    'serviceOrders.typeMessage': 'Type your message...',
    'serviceOrders.send': 'Send',
    'serviceOrders.sending': 'Sending...',
    'serviceOrders.noMessages': 'No messages yet',
    'serviceOrders.startConversation': 'Start the conversation by sending a message.',
    'serviceOrders.close': 'Close',
    'common.user': 'User',
    'common.details': 'Details',
    'common.viewAll': 'View All',
    'common.back': 'Back',
    'common.unread': 'unread',
    'common.paid': 'Paid',
    'serviceOrders.newMessages': 'New messages from admin',
    'serviceOrders.paymentLinkAvailable': 'Payment link available',
    'serviceOrders.readyForPayment': 'Ready for payment',
    'serviceOrders.payWithLink': 'Pay with Link',
    
    // Payments Page
    'payments.title': 'Payments',
    'payments.subtitle': 'View your payment history and statuses',
    'payments.loginRequired': 'Please log in to view your payments',
    'payments.loginButton': 'Login',
    'payments.loading': 'Loading payments...',
    'payments.noPayments': 'No payments yet',
    'payments.error': 'Failed to load payments',
    'payments.table.date': 'Date',
    'payments.table.order': 'Order',
    'payments.table.service': 'Service',
    'payments.table.amount': 'Amount',
    'payments.table.status': 'Status',
    'payments.table.method': 'Method',
    'payments.status.completed': 'completed',
    'payments.status.paid': 'paid',
    'payments.status.pending': 'pending',
    'payments.status.failed': 'failed',
    'payments.pagination.showing': 'Showing',
    'payments.pagination.of': 'of',
    'payments.pagination.page': 'Page',
    'payments.pagination.prev': 'Prev',
    'payments.pagination.next': 'Next'
  ,
  // Work With Us (Researcher)
  'work.title': 'Work With Us',
  'work.subtitle': 'Submit your idea or article overview and our team will get back to you.',
  'work.onlyResearchers': 'This page is available for researcher/professional users.',
  'work.why.title': 'Why work with ICSRT?',
  'work.why.1.title': 'Expert Mentorship',
  'work.why.1.desc': 'Collaborate with seasoned researchers and editors who guide your work to publication-ready quality.',
  'work.why.2.title': 'Publishing Support',
  'work.why.2.desc': 'From journal selection to revisions, we help you navigate the publication process.',
  'work.why.3.title': 'Real Impact',
  'work.why.3.desc': 'Join projects that solve real problems and contribute to the research community.',
  'work.why.4.title': 'Recognition',
  'work.why.4.desc': 'Your contributions are credited fairly with co-authorship or proper acknowledgment.',
  'work.form.title.label': 'Title',
  'work.form.title.placeholder': 'Your idea or article title',
  'work.form.summary.label': 'Summary',
  'work.form.summary.placeholder': 'Briefly describe your idea or article',
  'work.form.submit': 'Submit',
  'work.form.submitting': 'Submitting...',
  'work.form.done': 'Submitted!'
  },
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.services': 'الخدمات',
    'nav.articles': 'المقالات',
    'nav.about': 'عن المركز',
    'nav.faq': 'الأسئلة الشائعة',
    'nav.contact': 'اتصل بنا',
    'nav.login': 'تسجيل الدخول',
    'nav.signup': 'إنشاء حساب',
    'nav.profile': 'الملف الشخصي',
    'nav.dashboard': 'لوحة التحكم',
    'nav.logout': 'تسجيل الخروج',
  // Researcher
  'nav.work': 'اعمل معنا',
    
    // Homepage
    'hero.title.part1': 'المركز الدولي للبحوث',
    'hero.title.part2': 'العلمية والترجمة',
    'hero.description': 'تمكين التميز الأكاديمي من خلال المساعدة الخبيرة في البحوث.',
    'hero.btn.services': 'استكشف الخدمات',
    'hero.btn.learn': 'اعرف المزيد',
    'hero.badge': 'شريك البحث الموثوق',
    
    // Stats
    'stats.clients': 'عملاء',
    'stats.countries': 'دول مخدومة',
    'stats.success': 'مشاريع مكتملة',
    'stats.support': 'دعم 24/7',
    'stats.visitors': 'شركاء أكاديميون',
    
    // Services
    'services.title': 'خدماتنا',
    'services.subtitle': 'خدمات البحث والأكاديمية المهنية',
    'services.description': 'نحن نقدم خدمات البحث والدعم الأكاديمي الشامل',
    'services.view': 'عرض التفاصيل',
    'services.request': 'طلب الخدمة',
    'services.research.title': 'المساعدة البحثية',
    'services.research.desc': 'إرشاد خبير لمشاريعك البحثية من التصور إلى الإنجاز.',
    'services.translation.title': 'الترجمة المهنية',
    'services.translation.desc': 'ترجمات دقيقة من قبل لغويين معتمدين عبر لغات متعددة.',
    'services.graduation.title': 'مشاريع التخرج',
    'services.graduation.desc': 'دعم كامل لتطوير الأطروحة والرسالة.',
    'services.cta.title': 'هل أنت مستعد للبدء؟',
    'services.cta.description': 'اتصل بنا اليوم لمناقشة احتياجاتك البحثية والحصول على حل مخصص.',
    'services.cta.button': 'ابدأ الآن',
    
    // Common
    'common.loading': 'جاري التحميل...',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.search': 'بحث',
    'common.close': 'إغلاق',
    'common.settings': 'الإعدادات',
    
    // Form labels
    'form.name': 'الاسم الكامل',
    'form.email': 'البريد الإلكتروني',
    'form.phone': 'رقم الهاتف',
    'form.subject': 'الموضوع',
    'form.message': 'الرسالة',
    'form.category': 'التصنيف',
    'form.submit': 'إرسال',
    'form.send': 'إرسال الرسالة',
    'form.sending': 'جاري الإرسال...',
    
    // Contact
    'contact.title': 'اتصل بنا',
    'contact.subtitle': 'تواصل مع فريقنا',
    'contact.description': 'نحن هنا للمساعدة في احتياجاتك البحثية والأكاديمية',
    'contact.form.name': 'الاسم الكامل',
    'contact.form.email': 'البريد الإلكتروني',
    'contact.form.phone': 'رقم الهاتف',
    'contact.form.subject': 'الموضوع',
    'contact.form.message': 'الرسالة',
    'contact.form.category': 'التصنيف',
    'contact.form.submit': 'إرسال الرسالة',
    'contact.form.send': 'إرسال الرسالة',
    'contact.form.sending': 'جاري الإرسال...',
    'contact.form.namePlaceholder': 'أدخل اسمك الكامل',
    'contact.form.emailPlaceholder': 'أدخل بريدك الإلكتروني',
    'contact.form.phonePlaceholder': 'أدخل رقم هاتفك',
    'contact.form.subjectPlaceholder': 'وصف مختصر لاستفسارك',
    'contact.form.messagePlaceholder': 'اوصف احتياجاتك أو أسئلتك بالتفصيل',
    'contact.success': 'تم إرسال الرسالة بنجاح!',
    'contact.success.title': 'تم الإرسال!',
    'contact.success.message': 'شكراً لتواصلك معنا. سنرد عليك قريباً.',
    'contact.error': 'فشل في إرسال الرسالة. يرجى المحاولة مرة أخرى.',
    'contact.category.general': 'استفسار عام',
    'contact.category.services': 'معلومات الخدمات',
    'contact.category.technical': 'الدعم التقني',
    'contact.category.billing': 'الفواتير والمدفوعات',
    'contact.category.partnership': 'شراكة',
    'contact.info.email.title': 'راسلنا',
    'contact.info.email.value': 'info@icsrt-me.com',
    'contact.info.phone.title': 'اتصل بنا',
    'contact.info.phone.value': '+20 101 804 5506',
    'contact.info.response.title': 'وقت الاستجابة',
    'contact.info.response.value': 'خلال 24 ساعة',
    'contact.whatsapp': 'تحدث معنا على الواتساب',
    'contact.telegram': 'راسلنا على التيليجرام',
    'contact.submitTicket': 'إرسال تذكرة دعم',
    'contact.getHelp': 'احصل على مساعدة مهنية',
    
    // Articles
    'articles.title': 'المقالات البحثية',
    'articles.subtitle': 'أحدث الرؤى البحثية والمنشورات',
    'articles.view': 'اقرأ المزيد',
    'articles.read': 'اقرأ المقال',
    'articles.1.title': 'منهجية البحث الفعّالة للدراسات الأكاديمية المعاصرة',
    'articles.1.desc': 'اكتشف منهجيات شاملة لإجراء بحوث أكاديمية دقيقة في العصر الرقمي. تعلّم عن الأساليب المختلطة، واستراتيجيات جمع البيانات، والاعتبارات الأخلاقية التي تشكل أساس البحث العلمي الموثوق.',
    'articles.2.title': 'فن الترجمة العلمية: ربط اللغات في البحوث',
    'articles.2.desc': 'استكشف مجال الترجمة العلمية المتخصص حيث تلتقي الدقة بالخبرة اللغوية. فهم المصطلحات والفروق الثقافية والحفاظ على الدقة العلمية عبر الحواجز اللغوية في المنشورات الأكاديمية.',
    'articles.3.title': 'الأدوات والموارد الرقمية للبحث المعاصر',
    'articles.3.desc': 'تنقّل في مشهد أدوات البحث الحديثة بما في ذلك التحليل المدعوم بالذكاء الاصطناعي، ومنصات التعاون السحابية، وأنظمة إدارة الاستشهادات، وتقنيات تصور البيانات التي تعزز جودة وكفاءة البحث.',
    
    // About
    'about.title': 'عن المركز الدولي للبحوث العلمية والترجمة',
    'about.description': 'المركز الدولي للبحوث العلمية والترجمة - شريكك الموثوق في التميز الأكاديمي',
    'about.bio.title': 'قصتنا',
    'about.mission.title': 'مهمتنا',
    'about.mission.description': 'تقديم خدمات أكاديمية ودعم استثنائي للطلاب والباحثين والمؤسسات في جميع أنحاء العالم.',
    'about.vision.title': 'رؤيتنا',
    'about.vision.description': 'أن نصبح المنصة الدولية الرائدة لخدمات البحث العلمي والترجمة.',
    'about.approach.title': 'منهجنا',
    'about.excellence.title': 'التميز',
    'about.excellence.description': 'نحافظ على أعلى المعايير في البحث الأكاديمي والخدمات المهنية، مما يضمن أن كل مشروع يلبي معايير الجودة الدولية.',
    'about.collaboration.title': 'التعاون',
    'about.collaboration.description': 'نعمل بشكل وثيق مع الباحثين والمؤسسات والمجتمعات الأكاديمية حول العالم لتعزيز تبادل المعرفة والابتكار.',
    'about.innovation.title': 'الابتكار',
    'about.innovation.description': 'نتبنى التقنيات والمنهجيات المتطورة لتقديم حلول حديثة للتحديات البحثية المعاصرة.',
    'about.impact.title': 'تأثيرنا',
    'about.stats.clients': 'عملاء',
    'about.stats.countries': 'دول مخدومة',
    'about.stats.projects': 'مشاريع مكتملة',
    'about.stats.success': 'دعم',
    'about.cta.title': 'هل أنت مستعد لبدء رحلتك البحثية؟',
    'about.cta.description': 'انضم إلى آلاف الباحثين الذين يثقون بنا في نجاحهم الأكاديمي. دعنا نساعدك في تحقيق أهدافك البحثية.',
    'about.cta.services': 'استكشف خدماتنا',
    'about.cta.portal': 'الوصول لبوابة البحث',
    'about.learn.more': 'اعرف المزيد عنا',

    // Common translations
    'common.statistics': 'الإحصائيات',

    // Service request section
    'serviceRequest.title': 'طلب خدمة',
    'serviceRequest.subtitle': 'احصل على خدماتنا الأكاديمية المتخصصة',
    'serviceRequest.form.title': 'نموذج طلب الخدمة',
    'serviceRequest.form.fullName': 'الاسم الكامل',
    'serviceRequest.form.fullName.placeholder': 'ادخل اسمك الكامل',
    'serviceRequest.form.email': 'البريد الإلكتروني',
    'serviceRequest.form.email.placeholder': 'ادخل بريدك الإلكتروني',
    'serviceRequest.form.phone': 'رقم الهاتف',
    'serviceRequest.form.phone.placeholder': 'ادخل رقم هاتفك',
    'serviceRequest.form.serviceType': 'نوع الخدمة',
    'serviceRequest.form.serviceType.placeholder': 'اختر نوع الخدمة',
    'serviceRequest.form.serviceType.research': 'بحوث ومهام',
    'serviceRequest.form.serviceType.translation': 'خدمات الترجمة',
    'serviceRequest.form.serviceType.graduation': 'مشاريع التخرج',
    'serviceRequest.form.serviceType.thesis': 'رسائل الماجستير والدكتوراه',
    'serviceRequest.form.serviceType.editing': 'تحرير ومراجعة',
    'serviceRequest.form.serviceType.consultation': 'استشارات أكاديمية',
    'serviceRequest.form.urgency': 'درجة الأولوية',
    'serviceRequest.form.urgency.normal': 'عادي',
    'serviceRequest.form.urgency.urgent': 'عاجل',
    'serviceRequest.form.urgency.veryUrgent': 'عاجل جداً',
    'serviceRequest.form.projectDetails': 'تفاصيل المشروع',
    'serviceRequest.form.projectDetails.placeholder': 'اشرح تفاصيل المشروع أو الخدمة التي تحتاجها...',
    'serviceRequest.form.submit': 'إرسال طلب الخدمة',
    'serviceRequest.form.response': 'سيتم التواصل معك خلال 24 ساعة',
    'serviceRequest.login.required': 'يجب عليك تسجيل الدخول أولاً لتتمكن من طلب الخدمات',
    'serviceRequest.login.button': 'تسجيل الدخول',
    'serviceRequest.features.quick.title': 'استجابة سريعة',
    'serviceRequest.features.quick.desc': 'نرد خلال 24 ساعة',
    'serviceRequest.features.quality.title': 'جودة عالية',
    'serviceRequest.features.quality.desc': 'معايير أكاديمية عالمية',
    'serviceRequest.features.privacy.title': 'خصوصية تامة',
    'serviceRequest.features.privacy.desc': 'حماية كاملة لبياناتك',

    // Footer
    'footer.about.title': 'المركز الدولي للبحوث العلمية والترجمة',
    'footer.about.desc': 'المؤتمر الدولي للعلوم والبحوث والتكنولوجيا. تطوير المعرفة العلمية وتعزيز التعاون العالمي.',
  'footer.description': 'المؤتمر الدولي للعلوم والبحوث والتكنولوجيا. تطوير المعرفة العلمية وتعزيز التعاون العالمي.',
    'footer.quickLinks.title': 'روابط سريعة',
    'footer.quickLinks.about': 'عنا',
    'footer.quickLinks.events': 'الأحداث',
    'footer.quickLinks.papers': 'الأوراق البحثية',
    'footer.quickLinks.services': 'الخدمات',
    'footer.contact.title': 'التواصل',
    'footer.contact.email': 'البريد الإلكتروني: info@icsrt.org',
    'footer.contact.phone': 'الهاتف: +1 (555) 123-4567',
    'footer.contact.support': 'الدعم: support@icsrt.org',
    'footer.newsletter.title': 'ابق على اطلاع',
    'footer.newsletter.desc': 'اشترك في نشرتنا الإخبارية للحصول على آخر التحديثات.',
    'footer.newsletter.subscribe': 'اشترك',
    'footer.copyright': '© {year} ICSRT. جميع الحقوق محفوظة.',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.terms': 'شروط الخدمة',
    
    // Theme
    'theme.dark': 'التبديل للوضع المظلم',
    'theme.light': 'التبديل للوضع المضيء',
    
    // FAQ
    'faq.title': 'الأسئلة الشائعة',
    'faq.subtitle': 'اعثر على إجابات للأسئلة الشائعة حول خدماتنا',
    'faq.stillHaveQuestions': 'لا تزال لديك أسئلة؟',
    'faq.contactUs': 'نحن هنا لمساعدتك في أي أسئلة إضافية.',
    'faq.contactButton': 'اتصل بنا',
    
    // Login
    'login.welcome': 'مرحباً بعودتك',
    'login.subtitle': 'سجل دخولك إلى حسابك للوصول إلى جميع الميزات',
    'login.signing': 'جاري تسجيل الدخول...',
    'login.forgot': 'نسيت كلمة المرور؟',
    'login.no.account': 'ليس لديك حساب؟',
    'login.signup.link': 'سجل هنا',
    'form.login': 'تسجيل الدخول',
    'form.password': 'كلمة المرور',
  // Forgot / Reset Password
  'forgot.title': 'نسيت كلمة المرور',
  'forgot.subtitle': 'أدخل بريدك الإلكتروني لاستلام رابط إعادة التعيين',
  'forgot.submit': 'إرسال رابط إعادة التعيين',
  'forgot.sending': 'جاري الإرسال...',
  'forgot.sent': 'إذا كان هناك حساب لهذا البريد، فقد تم إرسال رابط إعادة التعيين.',
  'forgot.backToLogin': 'العودة لتسجيل الدخول',
  'reset.title': 'إعادة تعيين كلمة المرور',
  'reset.subtitle': 'أدخل كلمة مرور جديدة لحسابك',
  'reset.password': 'كلمة المرور الجديدة',
  'reset.confirm': 'تأكيد كلمة المرور الجديدة',
  'reset.submit': 'حفظ كلمة المرور الجديدة',
  'reset.saving': 'جاري الحفظ...',
  'reset.invalid': 'رابط إعادة التعيين غير صالح أو منتهي الصلاحية',
  'reset.success': 'تمت إعادة تعيين كلمة المرور. يمكنك الآن تسجيل الدخول.',
    
    // SignUp
    'signup.title': 'إنشاء حساب',
    'signup.subtitle': 'انضم إلى مجتمعنا البحثي',
    'signup.creating': 'جاري إنشاء الحساب...',
    'signup.already.account': 'لديك حساب بالفعل؟',
    'signup.login.link': 'سجل دخولك هنا',
    'form.signup': 'إنشاء حساب',
    'form.confirmPassword': 'تأكيد كلمة المرور',
    'form.institution': 'المؤسسة',
    'form.country': 'الدولة',
    'form.userType': 'نوع المستخدم',
    'form.userType.student': 'طالب',
    'form.userType.researcher': 'باحث',
    'form.userType.professor': 'أستاذ',
    'form.userType.other': 'أخرى',
    'signup.password.requirements': 'متطلبات كلمة المرور:',
    'signup.password.length': 'على الأقل 8 أحرف',
    'signup.password.uppercase': 'حرف كبير واحد',
    'signup.password.lowercase': 'حرف صغير واحد',
    'signup.password.number': 'رقم واحد',
    'signup.password.special': 'رمز خاص واحد',
    'signup.password.match': 'كلمات المرور يجب أن تتطابق',
    'signup.terms': 'أوافق على شروط الخدمة وسياسة الخصوصية',
    
    // Purchase Page
    'purchase.title': 'أكمل عملية الشراء',
    'purchase.loading': 'جاري تحميل تفاصيل الشراء...',
    'purchase.error': 'خطأ في تحميل تفاصيل الشراء',
    'purchase.invalid': 'رابط شراء غير صالح أو منتهي الصلاحية',
    'purchase.completed': 'تم إكمال الشراء بنجاح!',
    'purchase.orderSummary': 'ملخص الطلب',
    'purchase.billingInfo': 'معلومات الفواتير',
    'purchase.paymentMethod': 'طريقة الدفع',
    'purchase.couponCode': 'كود الخصم',
    'purchase.applyCoupon': 'تطبيق الخصم',
    'purchase.discount': 'الخصم',
    'purchase.subtotal': 'المجموع الفرعي',
    'purchase.total': 'المجموع',
    'purchase.processing': 'جاري معالجة الدفع...',
    'purchase.completePurchase': 'إكمال الشراء',
    
    // Email Verification
    'verification.title': 'تأكيد البريد الإلكتروني',
    'verification.subtitle': 'أدخل رمز التحقق المرسل إلى عنوان بريدك الإلكتروني.',
    'verification.email': 'البريد الإلكتروني',
    'verification.emailPlaceholder': 'أدخل عنوان بريدك الإلكتروني',
    'verification.code': 'رمز التحقق',
    'verification.codeHelp': 'أدخل الرمز المكون من 6 أحرف من بريدك الإلكتروني',
    'verification.verifying': 'جاري التحقق...',
    'verification.verify': 'تأكيد البريد الإلكتروني',
    'verification.didntReceive': 'لم تستلم الرمز؟',
    'verification.resend': 'إعادة إرسال بريد التحقق',
    'verification.backToLogin': 'العودة لتسجيل الدخول',
    'verification.success': 'تم تأكيد البريد الإلكتروني بنجاح! يمكنك الآن تسجيل الدخول.',
    'verification.error.required': 'البريد الإلكتروني ورمز التحقق مطلوبان.',
    'verification.error.network': 'خطأ في الشبكة. يرجى المحاولة مرة أخرى.',
    'verification.instructions.title': 'تعليمات التحقق',
    'verification.instructions.step1': 'تحقق من صندوق البريد الإلكتروني للحصول على رسالة تحقق من ICSRT',
    'verification.instructions.step2': 'انسخ رمز التحقق المكون من 6 أحرف من البريد الإلكتروني',
    'verification.instructions.step3': 'الصق الرمز في النموذج أعلاه أو انقر على رابط التحقق في البريد الإلكتروني',
    'verification.instructions.step4': 'تحقق من مجلد الرسائل غير المرغوب فيها إذا لم تر البريد الإلكتروني خلال بضع دقائق',
    
    // Loading and Common Messages
    'msg.loading': 'جاري التحميل...',
    
    // Articles
    'articles.read.more': 'اقرأ المزيد',
    
    // User Profile
    'profile.title': 'الملف الشخصي',
    'profile.info': 'معلومات الملف الشخصي',
    'profile.name': 'الاسم الكامل',
    'profile.email': 'البريد الإلكتروني',
    'profile.phone': 'رقم الهاتف',
    'profile.department': 'القسم',
    'profile.institution': 'المؤسسة',
    'profile.country': 'الدولة',
    'profile.bio': 'السيرة الذاتية',
    'profile.edit': 'تعديل الملف الشخصي',
    'profile.save': 'حفظ التغييرات',
    'profile.cancel': 'إلغاء',
    'profile.success': 'تم تحديث الملف الشخصي بنجاح!',
    'profile.error': 'فشل في تحديث الملف الشخصي',
    'profile.loading': 'جاري تحميل الملف الشخصي...',
    'profile.placeholder.name': 'أدخل اسمك الكامل',
    'profile.placeholder.phone': 'أدخل رقم هاتفك',
    'profile.placeholder.department': 'أدخل قسمك',
    'profile.placeholder.institution': 'أدخل مؤسستك',
    'profile.placeholder.country': 'أدخل دولتك',
    'profile.placeholder.bio': 'أخبرنا عن نفسك',
  'profile.changePassword.title': 'تغيير كلمة المرور',
  'profile.changePassword': 'تغيير كلمة المرور',
  'profile.currentPassword': 'كلمة المرور الحالية',
  'profile.newPassword': 'كلمة المرور الجديدة',
  'profile.confirmPassword': 'تأكيد كلمة المرور الجديدة',
  'profile.passwordChanged': 'تم تغيير كلمة المرور بنجاح!',
  'profile.passwordError': 'فشل تغيير كلمة المرور',
    
    // User Dashboard
    'dashboard.title': 'لوحة التحكم',
    'dashboard.welcome': 'مرحباً بعودتك',
    'dashboard.overview': 'نظرة عامة',
    'dashboard.stats.tickets': 'تذاكر الدعم',
    'dashboard.stats.orders': 'طلبات الخدمة',
    'dashboard.stats.projects': 'مشاريع نشطة',
    'dashboard.stats.messages': 'رسائل جديدة',
    'dashboard.recent.tickets': 'التذاكر الأخيرة',
    'dashboard.recent.orders': 'طلبات الخدمة الأخيرة',
    'dashboard.tickets.view': 'عرض جميع التذاكر',
    'dashboard.orders.view': 'عرض جميع الطلبات',
    'dashboard.tickets.create': 'إنشاء تذكرة جديدة',
    'dashboard.orders.create': 'طلب خدمة جديدة',
    'dashboard.ticket.id': 'رقم التذكرة',
    'dashboard.ticket.subject': 'الموضوع',
    'dashboard.ticket.status': 'الحالة',
    'dashboard.ticket.priority': 'الأولوية',
    'dashboard.ticket.created': 'تاريخ الإنشاء',
    'dashboard.order.number': 'رقم الطلب',
    'dashboard.order.service': 'الخدمة',
    'dashboard.order.status': 'الحالة',
    'dashboard.order.amount': 'المبلغ',
    'dashboard.order.date': 'التاريخ',
    'dashboard.status.open': 'مفتوح',
    'dashboard.status.progress': 'قيد التنفيذ',
    'dashboard.status.resolved': 'محلول',
    'dashboard.status.closed': 'مغلق',
    'dashboard.status.pending': 'قيد الانتظار',
    'dashboard.status.completed': 'مكتمل',
    'dashboard.status.cancelled': 'ملغي',
    'dashboard.priority.low': 'منخفض',
    'dashboard.priority.medium': 'متوسط',
    'dashboard.priority.high': 'عالي',
    'dashboard.priority.urgent': 'عاجل',
    'dashboard.no.tickets': 'لا توجد تذاكر',
    'dashboard.no.orders': 'لا توجد طلبات خدمة',
    'dashboard.loading': 'جاري تحميل لوحة التحكم...',
    'dashboard.todayActivity': 'إليك ما يحدث مع حسابك اليوم.',
    'dashboard.stats.supportTickets': 'تذاكر الدعم',
    'dashboard.stats.serviceOrders': 'طلبات الخدمة',
    'dashboard.recentTickets': 'التذاكر الأخيرة',
    'dashboard.recentServiceOrders': 'طلبات الخدمة الأخيرة',
    'dashboard.noTickets': 'لا توجد تذاكر بعد',
    'dashboard.createFirstTicket': 'إنشاء تذكرتك الأولى',
    'dashboard.noServiceOrders': 'لا توجد طلبات خدمة بعد',
    'dashboard.browseServices': 'تصفح خدماتنا',
    'dashboard.quickActions.supportTickets': 'تذاكر الدعم',
    'dashboard.quickActions.getHelp': 'احصل على المساعدة في أسئلتك',
    'dashboard.quickActions.serviceOrders': 'طلبات الخدمة',
    'dashboard.quickActions.viewRequests': 'عرض طلبات الخدمة الخاصة بك',
    'dashboard.quickActions.browseServices': 'تصفح الخدمات',
    'dashboard.quickActions.exploreOfferings': 'استكشف عروضنا',
    'dashboard.modal.serviceOrderDetails': 'تفاصيل طلب الخدمة',
    'dashboard.modal.orderInformation': 'معلومات الطلب',
    'dashboard.modal.orderNumber': 'رقم الطلب',
    'dashboard.modal.service': 'الخدمة',
    'dashboard.modal.status': 'الحالة',
    'dashboard.modal.submitted': 'تاريخ الإرسال',
    'dashboard.modal.totalAmount': 'المبلغ الإجمالي',
    'dashboard.modal.serviceDetails': 'تفاصيل الخدمة',
    'common.messages': 'رسالة',
    
    // Admin Dashboard
    'admin.dashboard.title': 'لوحة تحكم الإدارة',
    'admin.dashboard.welcome': 'مرحباً بك في لوحة الإدارة',
    'admin.dashboard.overview': 'نظرة عامة على النظام',
    'admin.dashboard.stats.users': 'إجمالي المستخدمين',
    'admin.dashboard.stats.tickets': 'تذاكر الدعم',
    'admin.dashboard.stats.orders': 'طلبات الخدمة',
    'admin.dashboard.stats.revenue': 'الإيرادات الشهرية',
    'admin.dashboard.stats.activeProjects': 'المشاريع النشطة',
    'admin.dashboard.stats.pendingReviews': 'المراجعات المعلقة',
    'admin.dashboard.recent.activity': 'النشاط الأخير',
    'admin.dashboard.recent.users': 'مستخدمون جدد',
    'admin.dashboard.recent.tickets': 'التذاكر الأخيرة',
    'admin.dashboard.recent.orders': 'الطلبات الأخيرة',
    'admin.dashboard.manage.users': 'إدارة المستخدمين',
    'admin.dashboard.manage.tickets': 'إدارة التذاكر',
    'admin.dashboard.manage.orders': 'إدارة الطلبات',
    'admin.dashboard.manage.services': 'إدارة الخدمات',
    'admin.dashboard.analytics': 'التحليلات',
    'admin.dashboard.reports': 'التقارير',
    'admin.dashboard.settings': 'إعدادات النظام',
    
    // Service Orders Page
    'serviceOrders.title': 'طلبات الخدمة الخاصة بي',
    'serviceOrders.subtitle': 'تتبع طلباتك وتواصل مع فريقنا',
    'serviceOrders.backToHome': 'العودة للرئيسية',
    'serviceOrders.backToDashboard': 'العودة للوحة التحكم',
    'serviceOrders.noOrders': 'لا توجد طلبات خدمة',
    'serviceOrders.noOrdersDesc': 'ستظهر طلبات الخدمة الخاصة بك هنا بمجرد تقديمها.',
    'serviceOrders.order': 'طلب',
    'serviceOrders.viewDetails': 'عرض التفاصيل',
    'serviceOrders.sendMessage': 'إرسال رسالة',
    'serviceOrders.purchase': 'اشتري الآن',
    'serviceOrders.details': 'التفاصيل',
    'serviceOrders.conversation': 'المحادثة',
    'serviceOrders.payment': 'الدفع',
    'serviceOrders.orderInfo': 'معلومات الطلب',
    'serviceOrders.serviceType': 'نوع الخدمة',
    'serviceOrders.status': 'الحالة',
    'serviceOrders.orderDate': 'تاريخ الطلب',
    'serviceOrders.lastUpdate': 'آخر تحديث',
    'serviceOrders.totalAmount': 'المبلغ الإجمالي',
    'serviceOrders.originalPrice': 'السعر الأصلي',
    'serviceOrders.discount': 'الخصم',
    'serviceOrders.finalPrice': 'السعر النهائي',
    'serviceOrders.messages': 'الرسائل',
    'serviceOrders.typeMessage': 'اكتب رسالتك...',
    'serviceOrders.send': 'إرسال',
    'serviceOrders.sending': 'جاري الإرسال...',
    'serviceOrders.noMessages': 'لا توجد رسائل بعد',
    'serviceOrders.startConversation': 'ابدأ المحادثة بإرسال رسالة.',
    'serviceOrders.close': 'إغلاق',
    'common.user': 'المستخدم',
    'common.details': 'التفاصيل',
    'common.viewAll': 'عرض الكل',
    'common.back': 'رجوع',
    'common.unread': 'غير مقروءة',
    'common.paid': 'مدفوع',
    'serviceOrders.newMessages': 'رسائل جديدة من الإدارة',
    'serviceOrders.paymentLinkAvailable': 'رابط الدفع متوفر',
    'serviceOrders.readyForPayment': 'جاهز للدفع',
    'serviceOrders.payWithLink': 'ادفع بالرابط',
    
    // Payments Page
    'payments.title': 'المدفوعات',
    'payments.subtitle': 'عرض سجل المدفوعات والحالات',
    'payments.loginRequired': 'يرجى تسجيل الدخول لعرض المدفوعات',
    'payments.loginButton': 'تسجيل الدخول',
    'payments.loading': 'جاري تحميل المدفوعات...',
    'payments.noPayments': 'لا توجد مدفوعات بعد',
    'payments.error': 'فشل في تحميل المدفوعات',
    'payments.table.date': 'التاريخ',
    'payments.table.order': 'الطلب',
    'payments.table.service': 'الخدمة',
    'payments.table.amount': 'المبلغ',
    'payments.table.status': 'الحالة',
    'payments.table.method': 'الطريقة',
    'payments.status.completed': 'مكتمل',
    'payments.status.paid': 'مدفوع',
    'payments.status.pending': 'قيد الانتظار',
    'payments.status.failed': 'فشل',
    'payments.pagination.showing': 'عرض',
    'payments.pagination.of': 'من',
    'payments.pagination.page': 'صفحة',
    'payments.pagination.prev': 'السابق',
    'payments.pagination.next': 'التالي'
  ,
  // Work With Us (Researcher)
  'work.title': 'اعمل معنا',
  'work.subtitle': 'أرسل فكرتك أو ملخص مقالتك وسيتواصل معك فريقنا.',
  'work.onlyResearchers': 'هذه الصفحة متاحة لمستخدمي الباحثين/المهنيين فقط.',
  'work.why.title': 'لماذا تعمل معنا؟',
  'work.why.1.title': 'إرشاد خبراء',
  'work.why.1.desc': 'تتعاون مع باحثين ومحررين ذوي خبرة يوجّهون عملك إلى جودة مناسبة للنشر.',
  'work.why.2.title': 'دعم النشر',
  'work.why.2.desc': 'من اختيار المجلة إلى المراجعات، نساعدك في اجتياز عملية النشر.',
  'work.why.3.title': 'أثر حقيقي',
  'work.why.3.desc': 'انضم إلى مشاريع تحل مشاكل واقعية وتساهم في المجتمع البحثي.',
  'work.why.4.title': 'تقدير مستحق',
  'work.why.4.desc': 'يتم توثيق مساهماتك بشكل عادل كمؤلف مشارك أو بإقرار مناسب.',
  'work.form.title.label': 'العنوان',
  'work.form.title.placeholder': 'عنوان الفكرة أو المقال',
  'work.form.summary.label': 'الملخص',
  'work.form.summary.placeholder': 'صف بإيجاز فكرتك أو مقالتك',
  'work.form.submit': 'إرسال',
  'work.form.submitting': 'جاري الإرسال...',
  'work.form.done': 'تم الإرسال!'
  }
};

export interface LanguageContextType {
  language: string;
  changeLanguage: (newLanguage: string) => void;
  t: (key: string) => string;
  isRTL: boolean;
  translations: Record<string, string>;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export interface LanguageProviderProps {
  children?: React.ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<string>('en');
  const [isRTL, setIsRTL] = useState<boolean>(false);

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') || 'en';
    setLanguage(savedLanguage);
    setIsRTL(savedLanguage === 'ar');
    document.dir = savedLanguage === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = savedLanguage;
  }, []);

  const changeLanguage = (newLanguage: string) => {
    setLanguage(newLanguage);
    setIsRTL(newLanguage === 'ar');
    localStorage.setItem('language', newLanguage);
    document.dir = newLanguage === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = newLanguage;
  };

  const t = (key: string): string => (translations as any)[language]?.[key] || key;

  const value: LanguageContextType = {
    language,
    changeLanguage,
    t,
    isRTL,
    translations: (translations as any)[language] || {}
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageProvider;
